export { default as Home } from './Home'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as FAQ } from './FAQ'
export { default as CreateDeck } from './CreateDeck'
export { default as MyDeck } from './MyDeck'